### ISSUE TITLE
Vibration Option?

### ISSUE THREAD

**Issue by Shy** [MahdiGharooni/holdable_button#6]
Would it be possible to add a vibration feature so you get a light haptic response while the button is being held.

**Comment by MahdiGharooni** [comment]
You're right, this package currently has basic features. We welcome contributions to enhance it with new features. Please feel free to submit a pull request or open an issue with your proposed additions.

**Comment by MahdiGharooni** [comment]
I've just added the Vibration Option to my package. Please check the 0.0.11 version.
Thanks for your suggestion.
